# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser as web
# import concurrent.futures
import app2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 292)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StopBot = QtWidgets.QPushButton(self.centralwidget)
        self.StopBot.setGeometry(QtCore.QRect(170, 180, 75, 23))
        self.StopBot.setObjectName("StopBot")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(90, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.info.setFont(font)
        self.info.setScaledContents(False)
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.show_scores = QtWidgets.QPushButton(self.centralwidget)
        self.show_scores.setGeometry(QtCore.QRect(170, 110, 75, 23))
        self.show_scores.setObjectName("show_scores")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setWindowIcon(QtGui.QIcon('Bot_Logo.png'))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.show_scores.clicked.connect(self.open_gsheets)
        self.StopBot.clicked.connect(self.toggle_onoff)

        self.BotState = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Win as Much as You Can Bot"))
        self.StopBot.setText(_translate("MainWindow", "Start Bot"))
        self.info.setText(_translate("MainWindow", "XY Telegram Bot is stopped."))
        self.show_scores.setText(_translate("MainWindow", "Show Scores"))


    def open_gsheets(self):
        if app2.game:
            web.open(f'https://docs.google.com/spreadsheets/d/1Hjlmt2Xe7579b4ym9NkdDEE56T5sW6EwXJQGAF_tUqk/edit#gid={app2.game.sheetid}')
        else:
            web.open('https://docs.google.com/spreadsheets/d/1Hjlmt2Xe7579b4ym9NkdDEE56T5sW6EwXJQGAF_tUqk/')

    def toggle_onoff(self):
        if self.BotState:
            self.info.setText('XY Telegram Bot is stopping. Please wait...')
            app2.stop_bot()
            self.info.setText('XY Telegram Bot is stopped.')
            self.StopBot.setText('Start Bot')
            self.BotState = False
        else:
            app2.start_bot()
            self.info.setText('XY Telegram Bot is running...')
            self.StopBot.setText('Stop Bot')
            self.BotState = True


# def main():
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())


# def start_app():
#     app2.start_bot()
#     print('start_app is run')


if __name__ == "__main__":
    #main()
    # with concurrent.futures.ThreadPoolExecutor() as executor:
    #     executor.submit(main)
    #     executor.submit(start_app)
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
